/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package createLibraryUtils;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertTrue;

public class LibraryTest {

    @Test public void isPositiveNumberTest() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.isPositiveNumber("5"),"someLibraryMethod should return 'true'");

    }
}
