/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package createLibraryUtils;

import org.apache.commons.lang3.math.NumberUtils;


public class Library {

    public static boolean isPositiveNumber(String str) {

        int num = NumberUtils.toInt(str);
        return num>0;
    }
}
